<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>LUME Audit Report</title>
    <style>
        @page { margin: 100px 25px; }
        body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 10pt; color: #333; }
        
        /* Header */
        header { position: fixed; top: -60px; left: 0px; right: 0px; height: 50px; border-bottom: 2px solid #ddd; }
        header .logo { float: left; font-weight: bold; font-size: 14pt; color: #4F46E5; }
        header .meta { float: right; font-size: 8pt; color: #777; text-align: right; }

        /* Footer */
        footer { position: fixed; bottom: -60px; left: 0px; right: 0px; height: 30px; border-top: 1px solid #ddd; text-align: center; font-size: 8pt; color: #999; }
        .page-number:after { content: counter(page); }

        /* Typography */
        h1 { font-size: 20pt; margin-bottom: 10px; color: #111; }
        h2 { font-size: 14pt; margin-top: 20px; margin-bottom: 10px; border-bottom: 1px solid #eee; padding-bottom: 5px; color: #444; }
        h3 { font-size: 11pt; margin-top: 15px; color: #555; }
        
        /* Executive Summary Box */
        .summary-box { background: #f9fafb; border: 1px solid #e5e7eb; padding: 15px; border-radius: 5px; margin-bottom: 20px; }
        .summary-text { font-style: italic; color: #4b5563; }
        
        /* Metadata Grid */
        .meta-grid { width: 100%; margin-bottom: 20px; }
        .meta-grid td { padding: 5px; width: 33%; vertical-align: top; }
        .meta-label { font-size: 8pt; color: #888; text-transform: uppercase; margin-bottom: 2px; }
        .meta-value { font-weight: bold; font-size: 10pt; }

        /* Risk Badge */
        .risk-badge { 
            display: inline-block; padding: 4px 8px; border-radius: 4px; color: white; font-weight: bold; font-size: 9pt; 
        }
        .risk-low { background-color: #10B981; }
        .risk-medium { background-color: #F59E0B; }
        .risk-high { background-color: #EF4444; }

        /* Tables */
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 9pt; }
        th { background-color: #f3f4f6; text-align: left; padding: 8px; border-bottom: 2px solid #e5e7eb; color: #374151; font-weight: 600; }
        td { padding: 8px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
        tr:nth-child(even) { background-color: #f9fafb; }
        
        /* Status Badges */
        .status-verified { color: #059669; font-weight: bold; }
        .status-risk { color: #DC2626; font-weight: bold; }
        .status-missing { color: #D97706; font-weight: bold; }

        /* Source Text (Smaller) */
        .source-text { font-size: 8pt; color: #6b7280; font-style: italic; display: block; margin-top: 3px; }

        /* Page Break Avoidance */
        tr { page-break-inside: avoid; }
    </style>
</head>
<body>
    <header>
        <div class="logo">LUME FORENSIC AUDIT</div>
        <div class="meta">
            Generated: {{ now()->toDateTimeString() }}<br>
            Asset ID: {{ $asset->id }}
        </div>
    </header>

    <footer>
        Confidential Audit Report &bull; Generated by Lume AI &bull; Page <span class="page-number"></span>
    </footer>

    <!-- TITLE PAGE -->
    <div style="margin-top: 20px;">
        <h1>{{ $asset->file_name }}</h1>
        <div class="summary-box">
            <div class="meta-label">EXECUTIVE SUMMARY</div>
            <div class="summary-text">
                {{ $audit['summary'] ?? "No summary available." }}
            </div>
        </div>

        <table class="meta-grid">
            <tr>
                <td>
                    <div class="meta-label">DOCUMENT TYPE</div>
                    <div class="meta-value">{{ $audit['document_type'] ?? 'Unknown' }}</div>
                </td>
                <td>
                    <div class="meta-label">PRIMARY LENS</div>
                    <div class="meta-value">{{ $audit['primary_lens'] ?? 'General' }}</div>
                </td>
                <td>
                    <div class="meta-label">RISK SCORE</div>
                    @php 
                        $score = $audit['audit_meta']['risk_score'] ?? 0;
                        $class = $score < 30 ? 'risk-low' : ($score < 70 ? 'risk-medium' : 'risk-high');
                    @endphp
                    <div class="risk-badge {{ $class }}">{{ $score }}/100</div>
                </td>
            </tr>
            <tr>
                <td>
                    <div class="meta-label">PAGES SCANNED</div>
                    <div class="meta-value">{{ $audit['audit_meta']['page_count'] ?? 0 }}</div>
                </td>
                <td>
                    <div class="meta-label">DETECTED LANGUAGE</div>
                    <div class="meta-value">{{ strtoupper($audit['audit_meta']['detected_language'] ?? 'EN') }}</div>
                </td>
                <td>
                    <div class="meta-label">PII STATUS</div>
                    <div class="meta-value" style="color: {{ ($audit['safety_checks']['pii_status'] ?? '') === 'DETECTED' ? '#DC2626' : '#059669' }}">
                        {{ $audit['safety_checks']['pii_status'] ?? 'UNKNOWN' }}
                    </div>
                </td>
            </tr>
        </table>
    </div>

    <!-- RISK FLAGS SECTION (High Importance) -->
    @php
        $risks = collect($facts)->filter(fn($f) => in_array($f['status'] ?? '', ['risk_flag', 'error', 'missing']));
    @endphp

    @if($risks->count() > 0)
        <h2>⚠️ Identified Risk Flags</h2>
        <table>
            <thead>
                <tr>
                    <th style="width: 15%">Severity</th>
                    <th style="width: 25%">Category</th>
                    <th style="width: 40%">Finding</th>
                    <th style="width: 20%">Location</th>
                </tr>
            </thead>
            <tbody>
                @foreach($risks as $risk)
                    <tr>
                        <td class="status-risk">{{ ucfirst($risk['status']) }}</td>
                        <td>
                            <strong>{{ $risk['category'] ?? 'General' }}</strong><br>
                            <span class="source-text">{{ $risk['context'] ?? '' }}</span>
                        </td>
                        <td>
                            {{ $risk['judgment'] ?? 'No detail provided.' }}
                            <span class="source-text">Source: "{{ \Illuminate\Support\Str::limit($risk['source_text'] ?? '', 100) }}"</span>
                        </td>
                        <td>{{ $risk['location'] ?? 'Unknown' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

    <!-- FULL AUDIT LOG (Grouped by Category for Readability) -->
    @php
        $verified = collect($facts)->filter(fn($f) => !in_array($f['status'] ?? '', ['risk_flag', 'error', 'missing']));
        $grouped = $verified->groupBy('category');
    @endphp

    <h2>✅ Verified Audit Facts</h2>
    @if($verified->count() === 0)
        <p>No additional verified facts found.</p>
    @else
        @foreach($grouped as $category => $items)
            <h3>{{ $category }}</h3>
            <table>
                <thead>
                    <tr>
                        <th style="width: 30%">Data Point</th>
                        <th style="width: 40%">Context & Verification</th>
                        <th style="width: 30%">Location</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($items as $item)
                        <tr>
                            <td>
                                <strong>{{ $item['data_point'] ?? '' }}</strong>
                            </td>
                            <td>
                                {{ $item['context'] ?? '' }}
                                @if(!empty($item['judgment']))
                                    <br><span class="source-text">Note: {{ $item['judgment'] }}</span>
                                @endif
                            </td>
                            <td>{{ $item['location'] ?? '' }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @endforeach
    @endif

</body>
</html>
